
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "left+-left*/nonassocMULnonassocDOTDIVDOTDIV MUL NUMBER VARstart : EXPRESSIONEXPRESSION : NUMBEREXPRESSION : VAREXPRESSION : EXPRESSION '+' EXPRESSION\n                  | EXPRESSION '-' EXPRESSIONEXPRESSION : EXPRESSION '*' EXPRESSION\n                  | EXPRESSION '/' EXPRESSION\n                  | EXPRESSION MUL EXPRESSIONEXPRESSION : EXPRESSION DOTDIV EXPRESSIONEXPRESSION : '(' EXPRESSION ']'"
    
_lr_action_items = {'NUMBER':([0,5,6,7,8,9,10,11,],[3,3,3,3,3,3,3,3,]),'VAR':([0,5,6,7,8,9,10,11,],[4,4,4,4,4,4,4,4,]),'(':([0,5,6,7,8,9,10,11,],[5,5,5,5,5,5,5,5,]),'$end':([1,2,3,4,13,14,15,16,17,18,19,],[0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-10,]),'+':([2,3,4,12,13,14,15,16,17,18,19,],[6,-2,-3,6,-4,-5,-6,-7,-8,-9,-10,]),'-':([2,3,4,12,13,14,15,16,17,18,19,],[7,-2,-3,7,-4,-5,-6,-7,-8,-9,-10,]),'*':([2,3,4,12,13,14,15,16,17,18,19,],[8,-2,-3,8,8,8,-6,-7,-8,-9,-10,]),'/':([2,3,4,12,13,14,15,16,17,18,19,],[9,-2,-3,9,9,9,-6,-7,-8,-9,-10,]),'MUL':([2,3,4,12,13,14,15,16,17,18,19,],[10,-2,-3,10,10,10,10,10,None,-9,-10,]),'DOTDIV':([2,3,4,12,13,14,15,16,17,18,19,],[11,-2,-3,11,11,11,11,11,11,None,-10,]),']':([3,4,12,13,14,15,16,17,18,19,],[-2,-3,19,-4,-5,-6,-7,-8,-9,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'EXPRESSION':([0,5,6,7,8,9,10,11,],[2,12,13,14,15,16,17,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> EXPRESSION','start',1,'p_start','test.py',44),
  ('EXPRESSION -> NUMBER','EXPRESSION',1,'p_expression_number','test.py',48),
  ('EXPRESSION -> VAR','EXPRESSION',1,'p_expression_var','test.py',52),
  ('EXPRESSION -> EXPRESSION + EXPRESSION','EXPRESSION',3,'p_expression_sum','test.py',57),
  ('EXPRESSION -> EXPRESSION - EXPRESSION','EXPRESSION',3,'p_expression_sum','test.py',58),
  ('EXPRESSION -> EXPRESSION * EXPRESSION','EXPRESSION',3,'p_expression_mul','test.py',64),
  ('EXPRESSION -> EXPRESSION / EXPRESSION','EXPRESSION',3,'p_expression_mul','test.py',65),
  ('EXPRESSION -> EXPRESSION MUL EXPRESSION','EXPRESSION',3,'p_expression_mul','test.py',66),
  ('EXPRESSION -> EXPRESSION DOTDIV EXPRESSION','EXPRESSION',3,'p_expression_do','test.py',69),
  ('EXPRESSION -> ( EXPRESSION ]','EXPRESSION',3,'p_expression_group','test.py',73),
]
